---
# tasks file for installBase
- name: begining installation time. Installation in progress...
  shell: echo `date`
- name: "install base packages"
  apt: 
    state: present
    pkg:
       # outils diagnotisc système
      - sysstat
      - lsof
      - iotop
      - lynx
      - openssh-server
      - python
      - rsync
      - net-tools
      - tree
      - unzip
      - vim
      - wget
      - curl
      - expect
      - tmux
      - screen
      - pv
# ouils diagnostics réseau et securité
      - strace
      - netcat
      - socat
      - tcpdump
      - nmap
      - hydra
      #benchmarck fs
      - fio
      # dev versioning
      - git
      - subversion
      - telnet      
      - virtualbox
      - openjdk-11-jdk
      - iotop
      
#ops tools     
      - python
      - ansible
      - httpie
      - docker.io
      - vagrant
      - sshfs
      - sshpass
      - davfs2
       # outils de dev
      
      #################### GUI ###################
      - gwenview
      - keepassx
      - filezilla
      - vlc
      - firefox
      - gparted
      - simple-scan
      - simplescreenrecorder
      - zoom
      
      
      # FUN part so mandatory #
      - units
      - figlet
      
- name: Download visual code package
  get_url: 
    url: https://az764295.vo.msecnd.net/stable/58bb7b2331731bf72587010e943852e13e6fd3cf/code_1.49.1-1600299189_amd64.deb
    dest: /tmp/vscode.deb
  when: ansible_distribution == 'Ubuntu'
    
- name: Install visual code
  apt: deb="/tmp/vscode.deb"
         
- name: Download last google-chrome package
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
       

- name: Download sublime text3 package
  get_url:
    url: https://download.sublimetext.com/sublime_text_3_build_3211_x64.tar.bz2
    dest: /tmp/sublime_text_3_build_3211_x64.tar.bz2

- name: Download dropbox client
  get_url:
    url: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
    dest: /tmp/dropbox_2020.03.04_amd64.deb
    
- name: Install google-chrome
  apt: deb="/tmp/dropbox_2020.03.04_amd64.deb"
    

- name: "ntp package"
  apt:
    pkg: ntp
    state: present

- name: apt update and upgrade
  apt:
    update_cache: yes
    upgrade: yes
    
- name: end installation time
  shell: echo `date`
