---
# tasks file for installBase
- name: "install base packages"
  apt: name={{item}} state=installed
  with_items:
       - git
       - jwhois
       - lsof
       - lynx
       - openssh-server
       - python
       - rsync
       - screen
       - subversion
       - sysstat
       - tree
       - unzip
       - vim
       - wget
       - virtualbox
       - gwenview
       - vlc
       - openjdk-11-jdk
       - net-tools
       - sysstat
       - ansible
       
       
  when: ansible_distribution == 'Ubuntu'

- name: "install base packages"
  yum: name={{ item }} state=present
  with_items:
  - git
  - whois
  - lsof
  - lynx
  - openssh-server
  - python
  - rsync
  - screen
  - subversion
  - sysstat
  - tree
  - unzip
  - vim
  - wget
  - iotop
  - strace
  - net-tools
  - nc
  - telnet
  - java-1.8.0-openjdk
- name: "ntp package"
  yum: name=ntp state=installed
  when: ansible_distribution == 'Centos'

- name: "ntp package"
  apt: name=ntp state=installed force=yes
  when: ansible_distribution == 'Ubuntu'

