---
# tasks file for installBase
- name: "install base packages"
  apt: name={{item}} state=present
  with_items:
       # outils diagnotisc système
       - sysstat
       - lsof
       - screen
       - tcpdump
       - iotop
       - lynx
       - openssh-server
       - python
       - rsync
       - net-tools
       - tree
       - unzip
       - vim
       - wget

       #benchmarck fs
       - fio
       # dev versioning
       - git
       - subversion
             
       - virtualbox
          
       - openjdk-11-jdk
       
#ops tools     
       - ansible
       - httpie
       - curl
       - docker.io
       - vagrant
        # outils de dev
       - tmux
       # GUI
       - gwenview
       - keepassx
       - filezilla
       - vlc
    
       
  when: ansible_distribution == 'Ubuntu'

- name: "install base packages"
  yum: name={{ item }} state=present
  with_items:
  - git
  - whois
  - lsof
  - lynx
  - openssh-server
  - python
  - rsync
  - screen
  - subversion
  - sysstat
  - tree
  - unzip
  - vim
  - wget
  - iotop
  - strace
  - net-tools
  - nc
  - telnet
  - java-1.8.0-openjdk
  - keepassx
  when: ansible_distribution == 'Centos'

  
- name: "ntp package"
  yum: name=ntp state=installed
  when: ansible_distribution == 'Centos'

- name: "ntp package"
  apt: name=ntp state=installed force=yes
  when: ansible_distribution == 'Ubuntu'

