---
# tasks file for installBase
- name: "install base packages"
  apt: 
    state: present
    pkg:
       # outils diagnotisc système
      - sysstat
      - lsof
      - screen
      - iotop
      - lynx
      - openssh-server
      - python
      - rsync
      - net-tools
      - tree
      - unzip
      - vim
      - wget
      - curl
      - expect
# ouils diagnostics réseau
      - strace
      - netcat
      - socat
      - tcpdump
      - nmap
      - hydra
      #benchmarck fs
      - fio
      # dev versioning
      - git
      - subversion
      - telnet      
      - virtualbox
      - openjdk-11-jdk
      - iotop
      
#ops tools     
      - ansible
      - httpie
      - docker.io
      - vagrant
       # outils de dev
      - tmux
      #################### GUI ###################
      - gwenview
      - keepassx
      - filezilla
      - vlc
      - firefox
      
- name: Download visual code package
  get_url: 
    url: https://az764295.vo.msecnd.net/stable/58bb7b2331731bf72587010e943852e13e6fd3cf/code_1.49.1-1600299189_amd64.deb
    dest: /tmp/vscode.deb
  when: ansible_distribution == 'Ubuntu'
    
- name: Install visual code
  apt: deb="/tmp/vscode.deb"
         
- name: Download last google-chrome package
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
    
- name: Install google-chrom
  apt: deb="/tmp/google-chrome-stable_current_amd64.deb"

###- name: "install base packages"
#  yum: name={{ item }} state=present
#  with_items:
#  - git
#  - whois
#  - lsof
#  - lynx
#  - openssh-server
#  - python
#  - rsync
#  - screen
#  - subversion
#  - sysstat
#  - tree
#  - unzip
#  - vim
#  - wget
#  - iotop
#  - strace
#  - net-tools
#  - nc
#  - telnet
#  - java-1.8.0-openjdk
#  - keepassx
#  when: ansible_distribution == 'Centos'
#
  
- name: "ntp package"
  apt:
    pkg: ntp
    state: present

- name: apt update and upgrade
  apt:
    update_cache: yes
    upgrade: yes
