---
# tasks file for installBase
- name: begining installation time. Installation in progress...
  shell: echo `date`
- name: "install base packages"
  apt: 
    state: present
    pkg:
       # outils diagnotisc système
      - sysstat
      - lsof
      - iotop
      - lynx
      - openssh-server
      - python
      - rsync
      - net-tools
      - tree
      - unzip
      - vim
      - wget
      - curl
      - expect
      - tmux
      - screen
      - pv
      - zip
# ouils diagnostics réseau et securité
      - strace
      - netcat
      - socat
      - tcpdump
      - nmap
      - hydra
      #benchmarck fs
      - fio
      # dev versioning
      - git
      - subversion
      - telnet      
      - virtualbox
      - openjdk-11-jdk
      - iotop
      - neovim
      - htop
      
#ops tools     
      - python
      - ansible
      - httpie
      - docker.io
      - vagrant
      - sshfs
      - sshpass
      - ssh-askpass
      - davfs2
      - apache2
       # outils de dev
      
      #################### GUI ###################
      - gwenview
      - keepassx
      - filezilla
      - vlc
      - firefox
      - gparted
      - simple-scan
      - simplescreenrecorder
      - chromium-browser
      #necessary for openfortigui
      - libqt5keychain1
      - gnome-tweaks
      
      
      # FUN part so mandatory #
      - units
      - figlet
      # Lecture ebook
      - calibre
      - pdfshuffler
      - mupdf
      
- name: Download visual code package
  get_url: 
    url: https://az764295.vo.msecnd.net/stable/58bb7b2331731bf72587010e943852e13e6fd3cf/code_1.49.1-1600299189_amd64.deb
    dest: /tmp/vscode.deb
    
- name: Install visual code
  apt: deb="/tmp/vscode.deb"

      
- name: Download sublime text3 package
  get_url:
    url: https://download.sublimetext.com/sublime_text_3_build_3211_x64.tar.bz2
    dest: /tmp/sublime_text_3_build_3211_x64.tar.bz2

- name: Download dropbox client
  get_url:
    url: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
    dest: /tmp/dropbox_2020.03.04_amd64.deb
    
- name: Download and install google-chrome
  apt: deb="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
    

- name: Download openfortigui client
  get_url:
    url: https://apt.iteas.at/iteas/pool/main/o/openfortigui/openfortigui_0.9.0-3_amd64_focal.deb
    dest: /tmp/openfortigui_0.9.0-3_amd64_focal.deb
    
- name: Install openfortigui
  apt: deb="/tmp/openfortigui_0.9.0-3_amd64_focal.deb"


- name: "ntp package"
  apt:
    pkg: ntp
    state: present

- name: apt update and upgrade
  apt:
    update_cache: yes
    upgrade: yes
    
- name: permit ssh root login
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PermitRootLogin yes"
    state: present
  notify:
    - restart sshd
       
- name: end installation time
  shell: echo `date`

handlers:
  - restart sshd
    name: sshd
    state: restarted
