---
# tasks file for docker
# Install docker
- name: Install docker
  package: name=docker.io state=latest

- name: enable docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: add current to docker group
  shell: usermod -aG docker lli 

